### ISSUE TITLE
Where is potx-cli.php?

### ISSUE THREAD

**Issue by oshevans** [kgaut/drupal-potx#1]
Hi, this is probably a stupid question, but you mention that we should 'Copy potx.inc and potx-cli.php to the directory ...', but 'potx-cli.php' isn't in the repo.

Thanks.

**Comment by kgaut** [comment]
Hi, 

This is a quick and dirty port for d8, the readme file is not accurate.

How to make it works ? 
- download this module in **modules** folder
- enable it : `drush en potx`
- extract translation with drush : `drush @ALIAS potx single --include=modules/contrib/potx/ --modules=MYMODULE_MACHINE_NAME --api=8`

**Comment by oshevans** [comment]
Thanks!
Working nicely.

I tried to change --module=MY_MOD to --theme=MY_THEME..
Am I doing something wrong, or does it not support themes?

**Comment by kgaut** [comment]
I don't know how it's supposed to work with theme, try to ask on this topic : https://www.drupal.org/node/2356469.

**Comment by davidgil** [comment]
With theme it works the same, if you run it in theme folder it extract all.

**Comment by vlledo** [comment]
If I run it from theme folder it process all Drupal files. To extract theme strings I use this command drush @ALIAS single --folder=themes/custom/THEME_NAME --api=8 --language=es
