### ISSUE TITLE
Potx Module is not compatible with drush 9.0.0-beta5+

### ISSUE THREAD

**Issue by zero2one** [kgaut/drupal-potx#6]
Drush 9 uses from version 9.0.0-beta5 a new way of defining drush commands.
See https://weitzman.github.io/blog/port-to-drush9

The potx module needs to implement the `drush.services.yml` file and a drush command class next to the existing code so it works on Drush 8 and 9.

**Comment by kgaut** [comment]
Merged thx !

**Comment by MPParsley** [comment]
Nice one.

@kgaut, to avoid maintaining the same code twice, you may want to refactor potx_drush_extract() to reuse PotxCommands.

See https://github.com/kgaut/drupal-potx/pull/8

**Comment by kgaut** [comment]
Merged too ! thx !

**Comment by zero2one** [comment]
@kgaut : The refactoring by @MPParsley broke the functionality for Drush 8:

The Drush 9 code is not the same as Drush 8: different API.

Potx is now broken for Drush 8…

**Comment by kgaut** [comment]
Merged, please confirm that the module is working fine on both Drush 8 & Drush 9 ?
